puts "The students of my cohort at Makers Academy"
puts "-------------"
puts "Nina Herring"
puts "Sam Becker"
puts "Sarah Lester"
puts "Mario Young"
puts "Ayse Barch"
puts "Linda Cooper"
puts "Deborah Jordan"
puts "Lucas Scott"
puts "Andrew Oates"
print "Overall, we have "
print 9
puts " great students"